name: check
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      rust: ${{ steps.changes.outputs.rust }}
      web: ${{ steps.changes.outputs.web }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            rust:
              - 'flake.nix'
              - 'flake.lock'
              - '.github/workflows/check.yml'
              - 'src/**'
              - 'Cargo.{toml,lock}'
              - '.cargo/**'
              - 'rustfmt.toml'
            web:
              - 'flake.nix'
              - 'flake.lock'
              - '.github/workflows/check.yml'
              - 'wit/**'
              - 'web/**'
  rust-check:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' }}
    steps:
      - uses: actions/create-github-app-token@v2
        id: app
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - run: echo "user-id=$(gh api "/users/${{ steps.app.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        id: user-id
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.app.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix develop -c 'bash' -c 'cargo fmt'
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: '${{ steps.app.outputs.app-slug }}[bot]'
          commit_user_email: '${{ steps.user-id.outputs.user-id }}+${{ steps.app.outputs.app-slug }}[bot]@users.noreply.github.com'
          commit_message: 'chore: cargo fmt'
      - run: nix build
  web-check:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix develop ..#web -c 'bash' -c 'dprint fmt --diff'
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: '${{ steps.app.outputs.app-slug }}[bot]'
          commit_user_email: '${{ steps.user-id.outputs.user-id }}+${{ steps.app.outputs.app-slug }}[bot]@users.noreply.github.com'
          commit_message: 'chore: dprint fmt'
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: "*"
          cache: pnpm
          cache-dependency-path: web/pnpm-lock.yaml
      - run: pnpm i
      - run: pnpm build
      - run: pnpm check
      - run: pnpm lint
