name: check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  id-token: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
      web: ${{ steps.filter.outputs.web }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            rust:
              - 'src/**'
              - 'Cargo.{toml,lock}'
              - 'rustfmt.toml'
            web:
              - 'with/**'
              - 'web/**'
  rust-fmt:
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.rust == 'true' }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix-develop -c 'bash' -c 'cargo fmt --check'
  rust-lint:
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.rust == 'true' }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix-develop -c 'bash' -c 'clippy'
  rust-build:
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.rust == 'true' }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix build
  web-fmt:
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.web == 'true' }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: |
          cd web
          nix-develop -c 'bash' -c 'dprint check'
  web-lint:
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.web == 'true' }}
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: "*"
          cache: pnpm
          cache-dependency-path: web/pnpm-lock.yaml
      - run: |
          cd web
          pnpm i
          pnpm lint
  web-build:
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.web == 'true' }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: "*"
          cache: pnpm
          cache-dependency-path: web/pnpm-lock.yaml
      - run: |
          cd web
          pnpm i
          pnpm build
